function CalcularIVA(IVA)
{ 
  CalcularIVA = 130 + 21%
    
}
console.log(CalcularIVA)


function CalcularIVA (CalcularProducto)
{
  let = CalcularIVA * 130/21%
  CalcularProducto - CalcularIVA
}
console.log( CalcularIVA(130))

//Punto2

function conviertoPesosaDolar(Valorpeso)
{
 calcular = (740 * Valorpeso )
 return resultado
}
console.log (conviertoPesosaDolar)

function conviertoDolaraPeso(Valordolar)
{
calcular = (Valordolar * 740)
return resultado

}
console.log (conviertoDolaraPeso)
    


